site_name: "TitanEd Docs"
theme:
  name: "material"  # This gives a clean UI
  logo: "images/logo.png"

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Configuration: configuration.md
  - API Reference: api.md
  - FAQ: faq.md
