site_name: "TitanEd Docs"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - toc.integrate
  palette:
    - scheme: default
    - scheme: slate
extra_css:
  - stylesheets/custom.css
nav:
  - Home: index.md
  - Studio:
      - Overview: Studio/studio.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Configuration: configuration.md
  - API Reference: api.md
  - FAQ: faq.md
