site_name: "TitanEd Docs"
theme:
  name: "material"
  palette:
    - scheme: slate  # 🔥 Dark Mode
      primary: orange  # 🟠 Primary Color
      accent: gray  # ⚫ Secondary Color
    - scheme: default  # 🌞 Light Mode
      primary: orange
      accent: gray
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - toc.integrate  # ✅ Enables right sidebar (Table of Contents)
  logo: "images/logo.png"
  extra_css:
    - stylesheets/custom.css  # Keep this only if you still need extra styling

nav:
  - Home: index.md
  - Studio:
      - Overview: Studio/studio.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Configuration: configuration.md
  - API Reference: api.md
  - FAQ: faq.md
