site_name: "TitanEd Docs"
theme:
  name: "windmill"
  palette: "dark"  # Choose "light", "dark", or "slate" for auto dark mode
  logo: "images/logo.png"
  extra_css:
    - stylesheets/custom.css  
  
nav:
  - Home: index.md
  - Studio:
      - Overview: Studio/studio.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Configuration: configuration.md
  - API Reference: api.md
  - FAQ: faq.md
