name: Deploy MkDocs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build MkDocs
        run: |
          cd docs
          mkdocs build -f mkdocs.yml

      - name: Ensure CNAME file exists
        run: |
          cd docs
          echo "docs.titaned.com" > site/CNAME
          echo "docs.titaned.com" > docs/site/CNAME

      - name: Check build output
        run: |
          cd docs
          ls -la site/

      - name: Deploy MkDocs
        run: |
          cd docs
          mkdocs gh-deploy --force -f mkdocs.yml
