name: Deploy MkDocs

on:
  push:
    branches:
      - master  # Change to "main" if using main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-bootstrap mkdocs-windwall

      - name: Build MkDocs
        run: mkdocs build -f docs/mkdocs.yml  # <-- Specify the correct path

      - name: Ensure CNAME file exists
        run: echo "docs.titaned.com" > docs/site/CNAME  # <-- Adjust path

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force -f docs/mkdocs.yml  # <-- Use the correct path
