name: Deploy MkDocs

on:
  push:
    branches:
      - master  # Change this to the branch you're deploying from (e.g., main or master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build MkDocs
        run: |
          mkdocs build -f mkdocs.yml  # No need to cd into docs if mkdocs.yml is in the root

      - name: Ensure CNAME file exists
        run: |
          echo "docs.titaned.com" > site/CNAME  # Place CNAME file in the generated site/ folder

      - name: Check build output
        run: |
          ls -la site/  # List contents of the site directory to verify the build output

      - name: Deploy MkDocs
        run: |
          mkdocs gh-deploy --force -f mkdocs.yml  # Deploy the site to GitHub Pages
